apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: daemonset-example
  labels:
    app: deamonset
spec:
  selector:
    matchLabels:
      name: deamonset-example
  template:
    metadata:
      labels:
        name: daemonset-example
  spec:
    containers:
      - name: daemonset-example
      image: tomcat:9.0-jdk8-adoptopenjdk-hotspot